version: '3'

services:
  backend:
    build: 
      context: .
    command: gunicorn mysite.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./Frontend/
    depends_on: 
      - backend
    ports: 
      - "80:80"
 