# Generated by Django 3.2 on 2021-04-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profilcategoryscore',
            name='description',
        ),
    ]
