# Generated by Django 3.2 on 2021-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210428_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='yearsOfExperience',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='profilcategoryscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=2, null=True),
        ),
    ]
