# Generated by Django 3.2 on 2021-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20210428_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='yearsOfExperience',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True),
        ),
    ]
