# Generated by Django 3.2 on 2021-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_profil_yearsofexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilcategoryscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True),
        ),
    ]
